name: aspiro_trade
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  auto_route: ^10.1.0+1
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0

  # Network
  dio: ^5.8.0+1
  retrofit: ^4.6.0

  # Logging
  talker: ^4.9.2
  talker_flutter: ^4.9.2
  talker_dio_logger: ^4.9.2
  talker_bloc_logger: ^4.9.2



  mask_text_input_formatter: ^2.9.0
  fl_chart: ^0.69.0
  realm: ^20.1.1
  flutter_secure_storage: ^9.2.4

  flutter_svg: ^2.2.1
  flutter_masked_text2: ^0.9.1
  firebase_core: ^4.2.0
  uuid: ^4.4.2
  candlesticks: ^2.1.0
  
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  in_app_purchase: ^3.2.3
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  intl: ^0.20.2
  firebase_auth: ^6.1.3
  crypto: ^3.0.7
  webview_flutter: ^4.13.1
  package_info_plus: ^9.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  retrofit_generator: '^9.7.0'
  json_serializable: ^6.9.5
  flutter_native_splash: ^2.4.7
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: "^0.14.4"


flutter:


  uses-material-design: true



  assets:
    - assets/svg/
    - assets/logo/
    - assets/html/
    - .env





flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpeg"
  min_sdk_android: 21 